project:
  type: website
  output-dir: _site

website:
  title: "ValidMind Release Notes"
  navbar:
    left:
      - text: cmvm
        href: cmvm.qmd
      - text: backend
        href: backend.qmd
      - text: frontend
        href: frontend.qmd
      - text: agents
        href: agents.qmd
      - text: validmind-library
        href: validmind-library.qmd
      - text: documentation
        href: documentation.qmd


format:
  html:
    theme: flatly
    toc: true

resources:
  - releases/**/* 